spring.application.name=springedumanager_2

# Permite que Spring interprete el parámetro
# oculto _method para utilizar PUT y DELETE
# desde formularios HTML.
spring.mvc.hiddenmethod.filter.enabled=true